id = "zed-penny"
name = "Penny"
description = "Penny language support for Zed"
version ="0.0.1"
schema_version = 1
authors = [
	"Sebastian Weaver <snotbane@pm.me>"
]
repository = "https://github.com/snotbane/zed-penny"

[grammars.penny]
repository = "https://github.com/snotbane/tree-sitter-penny"
rev = "54d5081ab1767d4a17e5ad5b3fdea4d695d14c0b"

[grammars.penny_dialog]
repository = "https://github.com/snotbane/tree-sitter-penny-dialog"
rev = "9e1ef8da381ffef97d149cbf0c05a4b3e07dd4f7"
