id = "zed-penny"
name = "Penny"
description = "Penny language support for Zed"
version ="0.0.1"
schema_version = 1
authors = [
	"Sebastian Weaver <snotbane@pm.me>"
]
repository = "https://github.com/snotbane/zed-penny"

[grammars.penny]
repository = "https://github.com/snotbane/tree-sitter-penny"
rev = "14f77fcbc7edf92a67e001d081545727abdcaf31"

[grammars.penny_dialog]
repository = "https://github.com/snotbane/tree-sitter-penny-dialog"
rev = "e1beaa7a8880fbbccffcfd7b0df1bc29fb31e461"
