name = "Penny Dialog"
grammar = "penny_dialog"
# This is not designed to be used, but for some reason, is required in order to ensure the language loads as an injection.
path_suffixes = ["penny_dialog"]
